	.arch armv7-a
	.eabi_attribute 27, 3
	.fpu neon
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 6
	.eabi_attribute 18, 4
	.file	"aecm_core_neon_offsets.c"
	.text
.Ltext0:
	.cfi_sections	.debug_frame
	.global	offset_aecm_dfaCleanQDomain
	.data
	.align	2
	.type	offset_aecm_dfaCleanQDomain, %object
	.size	offset_aecm_dfaCleanQDomain, 4
offset_aecm_dfaCleanQDomain:
	.word	13976
	.global	offset_aecm_outBuf
	.align	2
	.type	offset_aecm_outBuf, %object
	.size	offset_aecm_outBuf, 4
offset_aecm_outBuf:
	.word	15988
	.global	offset_aecm_xBuf
	.align	2
	.type	offset_aecm_xBuf, %object
	.size	offset_aecm_xBuf, 4
offset_aecm_xBuf:
	.word	15976
	.global	offset_aecm_dBufNoisy
	.align	2
	.type	offset_aecm_dBufNoisy, %object
	.size	offset_aecm_dBufNoisy, 4
offset_aecm_dBufNoisy:
	.word	15984
	.global	offset_aecm_dBufClean
	.align	2
	.type	offset_aecm_dBufClean, %object
	.size	offset_aecm_dBufClean, 4
offset_aecm_dBufClean:
	.word	15980
	.global	offset_aecm_channelStored
	.align	2
	.type	offset_aecm_channelStored, %object
	.size	offset_aecm_channelStored, 4
offset_aecm_channelStored:
	.word	15964
	.global	offset_aecm_channelAdapt16
	.align	2
	.type	offset_aecm_channelAdapt16, %object
	.size	offset_aecm_channelAdapt16, 4
offset_aecm_channelAdapt16:
	.word	15968
	.global	offset_aecm_channelAdapt32
	.align	2
	.type	offset_aecm_channelAdapt32, %object
	.size	offset_aecm_channelAdapt32, 4
offset_aecm_channelAdapt32:
	.word	15972
	.global	offset_aecm_real_fft
	.align	2
	.type	offset_aecm_real_fft, %object
	.size	offset_aecm_real_fft, 4
offset_aecm_real_fft:
	.word	17216
	.text
.Letext0:
	.file 1 "sources/modules/audio_processing/aecm/aecm_core_neon_offsets.c"
	.section	.debug_info,"",%progbits
.Ldebug_info0:
	.4byte	0x119
	.2byte	0x2
	.4byte	.Ldebug_abbrev0
	.byte	0x4
	.uleb128 0x1
	.4byte	.LASF19
	.byte	0x1
	.4byte	.LASF20
	.4byte	.LASF21
	.4byte	.Ltext0
	.4byte	.Letext0
	.4byte	.Ldebug_line0
	.4byte	.Ldebug_pubnames0
	.4byte	.Ldebug_pubtypes0
	.uleb128 0x2
	.byte	0x4
	.byte	0x5
	.ascii	"int\000"
	.uleb128 0x3
	.byte	0x4
	.byte	0x7
	.4byte	.LASF0
	.uleb128 0x3
	.byte	0x1
	.byte	0x8
	.4byte	.LASF1
	.uleb128 0x3
	.byte	0x1
	.byte	0x6
	.4byte	.LASF2
	.uleb128 0x3
	.byte	0x2
	.byte	0x5
	.4byte	.LASF3
	.uleb128 0x3
	.byte	0x2
	.byte	0x7
	.4byte	.LASF4
	.uleb128 0x3
	.byte	0x8
	.byte	0x5
	.4byte	.LASF5
	.uleb128 0x3
	.byte	0x8
	.byte	0x7
	.4byte	.LASF6
	.uleb128 0x3
	.byte	0x4
	.byte	0x7
	.4byte	.LASF7
	.uleb128 0x3
	.byte	0x4
	.byte	0x5
	.4byte	.LASF8
	.uleb128 0x3
	.byte	0x1
	.byte	0x8
	.4byte	.LASF9
	.uleb128 0x4
	.4byte	.LASF10
	.byte	0x1
	.byte	0x12
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_dfaCleanQDomain
	.uleb128 0x4
	.4byte	.LASF11
	.byte	0x1
	.byte	0x13
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_outBuf
	.uleb128 0x4
	.4byte	.LASF12
	.byte	0x1
	.byte	0x14
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_xBuf
	.uleb128 0x4
	.4byte	.LASF13
	.byte	0x1
	.byte	0x15
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_dBufNoisy
	.uleb128 0x4
	.4byte	.LASF14
	.byte	0x1
	.byte	0x16
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_dBufClean
	.uleb128 0x4
	.4byte	.LASF15
	.byte	0x1
	.byte	0x17
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_channelStored
	.uleb128 0x4
	.4byte	.LASF16
	.byte	0x1
	.byte	0x18
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_channelAdapt16
	.uleb128 0x4
	.4byte	.LASF17
	.byte	0x1
	.byte	0x19
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_channelAdapt32
	.uleb128 0x4
	.4byte	.LASF18
	.byte	0x1
	.byte	0x1a
	.4byte	0x2d
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	offset_aecm_real_fft
	.byte	0
	.section	.debug_abbrev,"",%progbits
.Ldebug_abbrev0:
	.uleb128 0x1
	.uleb128 0x11
	.byte	0x1
	.uleb128 0x25
	.uleb128 0xe
	.uleb128 0x13
	.uleb128 0xb
	.uleb128 0x3
	.uleb128 0xe
	.uleb128 0x1b
	.uleb128 0xe
	.uleb128 0x11
	.uleb128 0x1
	.uleb128 0x12
	.uleb128 0x1
	.uleb128 0x10
	.uleb128 0x6
	.uleb128 0x2134
	.uleb128 0x6
	.uleb128 0x2135
	.uleb128 0x6
	.byte	0
	.byte	0
	.uleb128 0x2
	.uleb128 0x24
	.byte	0
	.uleb128 0xb
	.uleb128 0xb
	.uleb128 0x3e
	.uleb128 0xb
	.uleb128 0x3
	.uleb128 0x8
	.byte	0
	.byte	0
	.uleb128 0x3
	.uleb128 0x24
	.byte	0
	.uleb128 0xb
	.uleb128 0xb
	.uleb128 0x3e
	.uleb128 0xb
	.uleb128 0x3
	.uleb128 0xe
	.byte	0
	.byte	0
	.uleb128 0x4
	.uleb128 0x34
	.byte	0
	.uleb128 0x3
	.uleb128 0xe
	.uleb128 0x3a
	.uleb128 0xb
	.uleb128 0x3b
	.uleb128 0xb
	.uleb128 0x49
	.uleb128 0x13
	.uleb128 0x3f
	.uleb128 0xc
	.uleb128 0x2
	.uleb128 0xa
	.byte	0
	.byte	0
	.byte	0
	.section	.debug_pubnames,"",%progbits
.Ldebug_pubnames0:
	.4byte	0x103
	.2byte	0x2
	.4byte	.Ldebug_info0
	.4byte	0x11d
	.4byte	0x7a
	.ascii	"offset_aecm_dfaCleanQDomain\000"
	.4byte	0x8c
	.ascii	"offset_aecm_outBuf\000"
	.4byte	0x9e
	.ascii	"offset_aecm_xBuf\000"
	.4byte	0xb0
	.ascii	"offset_aecm_dBufNoisy\000"
	.4byte	0xc2
	.ascii	"offset_aecm_dBufClean\000"
	.4byte	0xd4
	.ascii	"offset_aecm_channelStored\000"
	.4byte	0xe6
	.ascii	"offset_aecm_channelAdapt16\000"
	.4byte	0xf8
	.ascii	"offset_aecm_channelAdapt32\000"
	.4byte	0x10a
	.ascii	"offset_aecm_real_fft\000"
	.4byte	0
	.section	.debug_pubtypes,"",%progbits
.Ldebug_pubtypes0:
	.4byte	0xc7
	.2byte	0x2
	.4byte	.Ldebug_info0
	.4byte	0x11d
	.4byte	0x2d
	.ascii	"int\000"
	.4byte	0x34
	.ascii	"unsigned int\000"
	.4byte	0x3b
	.ascii	"unsigned char\000"
	.4byte	0x42
	.ascii	"signed char\000"
	.4byte	0x49
	.ascii	"short int\000"
	.4byte	0x50
	.ascii	"short unsigned int\000"
	.4byte	0x57
	.ascii	"long long int\000"
	.4byte	0x5e
	.ascii	"long long unsigned int\000"
	.4byte	0x65
	.ascii	"long unsigned int\000"
	.4byte	0x6c
	.ascii	"long int\000"
	.4byte	0x73
	.ascii	"char\000"
	.4byte	0
	.section	.debug_line,"",%progbits
.Ldebug_line0:
	.section	.debug_str,"MS",%progbits,1
.LASF5:
	.ascii	"long long int\000"
.LASF0:
	.ascii	"unsigned int\000"
.LASF18:
	.ascii	"offset_aecm_real_fft\000"
.LASF10:
	.ascii	"offset_aecm_dfaCleanQDomain\000"
.LASF13:
	.ascii	"offset_aecm_dBufNoisy\000"
.LASF16:
	.ascii	"offset_aecm_channelAdapt16\000"
.LASF7:
	.ascii	"long unsigned int\000"
.LASF6:
	.ascii	"long long unsigned int\000"
.LASF21:
	.ascii	"/home/build/code.Proj/csip/CSipSimple/jni/webrtc\000"
.LASF11:
	.ascii	"offset_aecm_outBuf\000"
.LASF20:
	.ascii	"sources/modules/audio_processing/aecm/aecm_core_neo"
	.ascii	"n_offsets.c\000"
.LASF1:
	.ascii	"unsigned char\000"
.LASF15:
	.ascii	"offset_aecm_channelStored\000"
.LASF9:
	.ascii	"char\000"
.LASF8:
	.ascii	"long int\000"
.LASF12:
	.ascii	"offset_aecm_xBuf\000"
.LASF19:
	.ascii	"GNU C 4.6 20120106 (prerelease)\000"
.LASF4:
	.ascii	"short unsigned int\000"
.LASF2:
	.ascii	"signed char\000"
.LASF14:
	.ascii	"offset_aecm_dBufClean\000"
.LASF3:
	.ascii	"short int\000"
.LASF17:
	.ascii	"offset_aecm_channelAdapt32\000"
	.ident	"GCC: (GNU) 4.6 20120106 (prerelease)"
	.section	.note.GNU-stack,"",%progbits
